---
name: Deploy to testnet

"on":
  push:

jobs:
  test:
    runs-on: ubuntu-20.04

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Sops Binary Installer
        uses: mdgreenwald/mozilla-sops-action@v1.1.0
        with:
          version: '<version>' # default is latest stable
        id: install
      - name: install gpg
        run: apt update && apt install gpg
      - name: test
        run: sops
