---
name: Deploy to testnet

"on":
  push:

jobs:
  test:
    runs-on: ubuntu-20.04

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Sops Binary Installer
        uses: mdgreenwald/mozilla-sops-action@v1.1.0
        # with:
        #   version: '<version>' # default is latest stable
        id: install
      - name: Import GPG key
        id: import_gpg
        uses: crazy-max/ghaction-import-gpg@v4
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}

      - name: test
        run: gpg --list-keys
      - name: test2
        run: sops -d foo.sops.yaml
